
#h4rpro setup
 
# Common
log_dir: "../logs"
data_dir: "C:/Users/abaker/Documents/Data"
name: "Guider"

# Save settings
file_format: "FITS"

# for run_guiding telnet
HOST_IP: 10.200.99.2
PORT: 49200
TIMEOUT: 100

# test IP
#HOST_IP: 127.0.0.1
#PORT: 5005
